#!/bin/bash

#Installiere Cerbot und Apache2
apt update && apt upgrade
apt install certbot apache2

#Domain und Email abfragen
read -p 'Type Domain (domain.name): ' domainName
read -p 'Type Email: ' emailAddress

#Zertifikat erstellen
certbot certonly --domain $domainName --email $emailAddress --agree-tos --non-interactive

#SSL Weiterleitung auf Apache2 konfigurieren
a2enmod ssl
a2ensite default-ssl
systemctl restart apache2
